### PR TITLE
namespace support

### PR DESCRIPTION
**Pull request by asfktz**
adding namespace support

usage:
var isolatedStorage1 = $localStorage.$namespace(‘isolatedStorage1’);
var isolatedStorage2 = $localStorage.$namespace(‘isolatedStorage2’);

### CODE REVIEW

**Comment by sompylasar** [comment]
@asfktz This repo is not maintained, please find an alternative. E.g. https://github.com/grevory/angular-local-storage or https://github.com/tymondesigns/angular-locker

**Comment by asfktz** [comment]
Yes, I see now. such a shame. I love this module. I use it every day.

**Comment by egilkh** [comment]
Closing as keyPrefix can be set during config now. See https://github.com/gsklee/ngStorage/pull/126

**Comment by williamboman** [comment]
@asfktz This is done, but only globally now. I was planning on doing something like what you've done.

**Pull request closed without merging**
