### PR TITLE
Release 0.3.8

### LINKED ISSUE #139: Create release 0.3.8
Should we wait for more fixes?

I'd like to take a stab at 
1. browserify (maybe we can put that to rest)
2. Better handling in IE as it seems to still be a sore point for many users. 

If no one complains I'll do 0.3.8 tomorrow and get working on the rest :)

### PR DESCRIPTION
**Pull request by egilkh**
Should fix #139

### CODE REVIEW

**Comment by williamboman** [comment]
Feels like it should have been a `0.4.0` considering the amount and nature of `0.3.7..HEAD` changes? Anyways, :+1: thanks!

**Comment by egilkh** [comment]
You are right it should have :) 

But I was thinking since the public api part that most people use hasn't been impacted (only more to be used if you want) it might have been confusing. On the other hand, most people probably won't notice if it's 0.3.8 or 0.4.0 :)

**Comment by williamboman** [comment]
The move over to providers might cause some issues for people. The official [semver](http://semver.org/) page dictates that `MINOR` should be bumped when
> [...] you add functionality in a backwards-compatible manner

Anyways, tomayto tomahto :smile:.

**Comment by egilkh** [comment]
Damn it! You win :smiley:

**Pull request merged**
