### PR TITLE
Exposes supported / $supported

### PR DESCRIPTION
**Pull request by OverZealous**
- Provides the ability to determine if the specified storage provider is supported or not (both before and after initialization)
- Prevents errors with `storageProvider.set`/`.get` erroring if it is not supported.

### CODE REVIEW

**Comment by OverZealous** [comment]
Forgot to mention, this closes #190

**Comment by simison** [comment]
@gsklee any changes getting this in?

**Comment by gsklee** [comment]
Thanks @OverZealous!

**Comment by gsklee** [comment]
@OverZealous Got some error report though, could you please take a look at this?

https://travis-ci.org/gsklee/ngStorage/builds/111410195

**Comment by OverZealous** [comment]
That's weird.  When I run the tests locally, it works fine.  Have you tried restarting the build in Travis?  Sometimes Travis just fails.

Especially since the build succeeded on my PR.

**Pull request merged**
