### PR TITLE
synchronize storage before unloading page

### LINKED ISSUE #124: Saving to storage and redirecting results in storage not being updated (zero $timeout doesn't help)
I have 2 routes with different templates / controllers, I have this code in first controller:

```
    $scope.$storage = $localStorage;

    $scope.editVideoTemplate = function (videoTemplate) {
        $scope.$storage.videoTemplate = videoTemplate;
        $timeout(function() { $location.path('/editor'); });
    }
```

The first time editVideoTemplate is run videoTemplate gets saved in localStorage, but on consequent runs (selecting different videoTemplates) it fails to update the value in localStorage. So after initial save, EditorCtrl always gets initially saved videoTemplate from localStorage.

If I add 300ms timeout (instead of zero), it works as it should - videoTemplate gets saved and successfully retrieved every time.

Can we have direct setters / getters for these edge cases, when there's no point to force user to wait and force digest cycle?

### PR DESCRIPTION
**Pull request by ProLoser**
Fixes #124 #116

### CODE REVIEW

**Comment by ProLoser** [comment]
Sorry about the brief flutter of activity. I decided that instead of resolving conflicts and working off of other's PR's, I'd work off the latest master. Since you seem to have a new `$sync()` function, I just added a call to that when the page unloads to essentially 'flush' the debounce. I could add more checks and do this left often but I figured it's not really necessary.

**Comment by egilkh** [comment]
Hey ProLoser! Thanks for the contribution. 

Are you aware that $sync does not write down to the webStorage? It just reads up from webStorage.

**Comment by ProLoser** [comment]
Damn, no I was unaware. Crap...

Do we still need to do @wrfel's solution or did you add  it yourself?

**Comment by ProLoser** [comment]
@egilkh I actually think that $sync should be replaced with $apply since you merged the other solution too. I was not trying to update the $localStorage object, I was trying to update the window's localstorage at unload. There is no reason to update the factory's object when the page is about to close.

**Comment by egilkh** [comment]
Agreed, Have pushed new code.

**Pull request closed without merging**
